### ISSUE TITLE
hosts get always "let`s encrypt acme" annotation

### ISSUE THREAD

**Issue by thesephirot** [caos/orbos#207]
Wenn a host kind is set with a static certificate, the acme call is added always.

this should not happen, as 2 certs are configured then.

**Comment by stebenz** [comment]
![image](https://user-images.githubusercontent.com/46600784/84472411-68617000-ac87-11ea-8a6a-9e38a8fb0ff0.png)
This situation is solved with "acmeProvider.authority: none"
