### ISSUE TITLE
Node Reboot Flag

### ISSUE THREAD

**Issue by fforootd** [caos/orbos#266]
I would like to have a flag which can reboot a certain node gracefully.

E.g, `reboot-required: true` in the orbiter.yml

**Comment by eliobischof** [comment]
That's a one-time operation. What about `orbctl exec <node> --command 'sudo reboot'`?

**Comment by fforootd** [comment]
Ok @eliobischof this works for most cases, but i would also like to handle cases where the SSH Daemon is `dead`.
