### ISSUE TITLE
New Provider Cloudscale

### ISSUE THREAD

**Issue by fforootd** [caos/orbos#364]
We should implement https://www.cloudscale.ch/en/ as an additional provider

@eliobischof please eval. if it is possible

**Comment by fforootd** [comment]
Further Infos

https://www.cloudscale.ch/en/api/v1
https://github.com/cloudscale-ch/cloudscale-go-sdk

**Comment by fforootd** [comment]
Storageclass would also be important https://github.com/cloudscale-ch/csi-cloudscale

**Comment by eliobischof** [comment]
merged in #452
