### ISSUE TITLE
support filter type plugin for ambassador

### ISSUE THREAD

**Issue by davidamin-B** [caos/orbos#642]
Would be cool if BOOM could load `.so` files from a git repo into the edge stack containers at `/etc/ambassador-plugins/${NAME}.so` to allow the use of custom filter plugins (https://www.getambassador.io/docs/pre-release/topics/using/filters/plugin/#filter-type-plugin).

Alternatively as mentioned in #621 support custom docker images.

**Comment by goir** [comment]
We actually need this feature and considering implementing this.
What would be the best way to do this.
A custom image or provide the plugin .so file somehow ?

Since the .so is tightly coupled to the version and abi of the ambassador a custom image would be the easiest and best  way i guess ?

**Comment by stebenz** [comment]
@daveboe in #621 unfortunately there was no mention of custom docker images but just to overwrite the image-versions. Anyway, I added the option to overwrite the image in the PR as well. 

@goir In my opinion the option with a custom image would be prefered, as the functionality here is not meant to include any special git clones or other reconciling functionality but to read one single yaml-file and use it to configure a set of tools. In addition, maintaining the image separately would be easier than to include the specific logic in orbos to the testing as well.
